#ifndef __CONFIG_HPP__
#define __CONFIG_HPP__

#define PROTOCOL_MESSAGE_DELIMITER '\n'
#define PROTOCOL_UID_SIZE (6)
#define PROTOCOL_PASSWORD_SIZE (8)
#define PROTOCOL_AID_SIZE (3)

#define DEFAULT_HOSTNAME "127.0.0.1"
#define DEFAULT_PORT "58085"

#endif