#ifndef __CONFIG_HPP__
#define __CONFIG_HPP__

#define PROTOCOL_MESSAGE_DELIMITER '\n'
#define PROTOCOL_UID_SIZE (6)
#define PROTOCOL_PASSWORD_SIZE (8)
#define PROTOCOL_AID_SIZE (3)
#define PROTOCOL_ERROR_IDENTIFIER "ERR"
#define PROTOCOL_MAX_FILE_SIZE 10000000

#define DEFAULT_HOSTNAME "127.0.0.1"
#define DEFAULT_PORT "58085"

#define SOCKETS_MAX_DATAGRAM_SIZE_CLIENT (6001)
#define SOCKETS_MAX_DATAGRAM_SIZE_SERVER (6001)
#define SOCKETS_TCP_BUFFER_SIZE (512)
#define SOCKETS_UDP_TIMEOUT (5)

#endif